### ISSUE TITLE
issue when filename contains percent sign

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#11]
**Describe the issue**
received from a beta tester: "
An mp3-file failed to be indexed, with the error: I/O exception while building library
The program just hung indefinitely with no UI feedback, apart from the logs written to the USB drive.
Removing the suspect mp3-file "fixed" the problem. The problem seems to be the "%" character in the Album tag in the mp3 file and/or in the mp3-file path."

**Expected behavior**
"Special characters should be supported in the file tags."

**AudioWagon version**
0.2.5

**Logfiles**
```
2021-09-14 10:19:25.447 [DEBUG   ][15935][AudioMetadataMaker  ] Extracting metadata for: AudioFile(uri=usbAudio://1921-21909/Music/100% Rock Volume 1 CD1/01-Golden Earring-Radar Love.mp3)
2021-09-14 10:19:25.462 [DEBUG   ][15913][AudioBrowserService ] onLoadChildren(parentId=/)
2021-09-14 10:19:25.468 [DEBUG   ][15933][AudioItemLibr       ] Requested MediaItem content hierarchy from library: /
2021-09-14 10:19:25.471 [DEBUG   ][15933][AudioBrowserService ] Got 3 mediaItems in onLoadChildren(parentId=/)
2021-09-14 10:19:25.475 [ERROR   ][15935][AudioBrowserService ] I/O exception while building library
2021-09-14 10:19:25.475 [ERROR   ][15935][AudioBrowserService ] java.io.IOException: USB file not found: usbAudio://1921-21909/Music/100% Rock Volume 1 CD1/01-Golden Earring-Radar Love.mp3
2021-09-14 10:19:25.475 [ERROR   ][15935][AudioBrowserService ] 	at b.a.a.v.n.q.h(USBMediaDevice.kt:9)
2021-09-14 10:19:25.475 [ERROR   ][15935][AudioBrowserService ] 	at b.a.a.v.n.l.b(USBDeviceStorageLocation.kt:3)
2021-09-14 10:19:25.475 [ERROR   ][15935][AudioBrowserService ] 	at b.a.a.a.f.a(AudioMetadataMaker.kt:9)
2021-09-14 10:19:25.475 [ERROR   ][15935][AudioBrowserService ] 	at b.a.a.a.c.b(AudioItemLibrary.kt:16)
2021-09-14 10:19:25.475 [ERROR   ][15935][AudioBrowserService ] 	at b.a.a.a.c$a.n(Unknown Source:12)
2021-09-14 10:19:25.475 [ERROR   ][15935][AudioBrowserService ] 	at c.v.j.a.a.k(ContinuationImpl.kt:3)
2021-09-14 10:19:25.475 [ERROR   ][15935][AudioBrowserService ] 	at h.a.j0.run(DispatchedTask.kt:18)
2021-09-14 10:19:25.475 [ERROR   ][15935][AudioBrowserService ] 	at h.a.e2.a.L(CoroutineScheduler.kt:1)
2021-09-14 10:19:25.475 [ERROR   ][15935][AudioBrowserService ] 	at h.a.e2.a$a.run(CoroutineScheduler.kt:11)

```

**Comment by MoleMan1024** [comment]
This has been fixed in version 0.3.4.
