### ISSUE TITLE
voice input doesn't work

### ISSUE THREAD

**Issue by BenPicard** [MoleMan1024/audiowagon#119]
**Describe the issue**
I just got delivery of my XC60 2023 with AA. This app is fantastic but voice input commands are not working. Everytime that I ask for a song or artist, it's telling me that YouTube music is not installed.

**Expected behavior**
Play what I asked for.

**AudioWagon version**
Lastest

**Car version**
Will check tomorrow but it's the latest build of AA

Thank you!

**Comment by MoleMan1024** [comment]
@BenPicard : Did you make sure AudioWagon was running while using voice commands as explained [here](https://moleman1024.github.io/audiowagon/faq.html#does-the-app-support-voice-input) ? 

In general this is not something I can fix but is implemented by Google (the whole voice recognition is done by Google). I only forward whatever speech text was detected and put that into the AudioWagon search.

**Comment by BenPicard** [comment]
Yes, AudioWagon was running.
I even deleted other media app to try.

**Comment by BenPicard** [comment]
@MoleMan1024 So i'm a bit close to make it works! 
I opened the Google Assistant app on my iPhone and i was able to unselect YouTube Music in the music tab.

Now, when I ask for a song or artist, i get the following: "Perfect, we will ask AudioWagon to play *artist name*"

The problem is now that it stops there. No music is starting. I testing with multiple name and song, in English and in French. The behavior is the same.

**Comment by MoleMan1024** [comment]
@BenPicard : ok, please provide a log file to me (attach into write box here or to my e-mail) as described [here](https://moleman1024.github.io/audiowagon/#how-do-i-report-an-issue). I can have a look if anything is arriving on AudioWagon side.

**Comment by BenPicard** [comment]
@MoleMan1024 

Here's 2 logs.
I tried to delete and reinstall AudioWagon but it was the same.

AA version is 2.9 and AW version is 2.3.10

Also did a small recording for you to see the behavior : [https://partage.picard.ca/IMG_1670](https://partage.picard.ca/IMG_1670)

[audiowagon_2023-05-26_13-05-16.log](https://github.com/MoleMan1024/audiowagon/files/11578359/audiowagon_2023-05-26_13-05-16.log)
[audiowagon_2023-05-26_13-10-25.log](https://github.com/MoleMan1024/audiowagon/files/11578360/audiowagon_2023-05-26_13-10-25.log)

**Comment by MoleMan1024** [comment]
@BenPicard : thank you for the logs.

So Google Assitant gave AudioWagon the artist "Billy Talent":

`
2023-05-26 13:04:52.339 [DEBUG   ][8320-8320  ][AudioSessCB             ] onPlayFromSearch(query=Billy Talent,extras=Bundle[mParcelledData.dataSize=740])
...
2023-05-26 13:04:52.341 [DEBUG   ][8320-31025 ][AudioSessCB             ] notifyObservers(AudioSessionChange(type=ON_PLAY_FROM_SEARCH, queueID=-1, contentHierarchyID='', artistToPlay='Billy Talent', albumToPlay='', trackToPlay='', queryToPlay='Billy Talent', queryFocus='ARTIST' equalizerPreset='', metadataReadSetting='', audioFocusSetting='', albumStyleSetting=''))

and then something went wrong:

2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] Invalid content hierarchy: ContentHierarchyID(type=ARTIST, storage=4C531001581129-1921-21889, trk=-1, art=-99, albArt=14, alb=-99, trkGrp=-1, artGrp=-1, albGrp=-1, path=, dirGrp=-1)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] java.lang.IllegalArgumentException: Invalid content hierarchy: ContentHierarchyID(type=ARTIST, storage=4C531001581129-1921-21889, trk=-1, art=-99, albArt=14, alb=-99, trkGrp=-1, artGrp=-1, albGrp=-1, path=, dirGrp=-1)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at de.moleman1024.audiowagon.player.AudioSession$observePlaybackQueue$1$1.invokeSuspend(AudioSession.kt:400)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at de.moleman1024.audiowagon.player.AudioSession$observePlaybackQueue$1$1.invoke(Unknown Source:8)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at de.moleman1024.audiowagon.player.AudioSession$observePlaybackQueue$1$1.invoke(Unknown Source:4)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at de.moleman1024.audiowagon.SingletonCoroutine$launch$job$1.invokeSuspend(SingletonCoroutine.kt:64)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2023-05-26 13:04:52.388 [ERROR   ][8320-31025 ][SglCoRt|ObservPlaybQ    ] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)


`

**Comment by BenPicard** [comment]
Thank you so much for the fast support. I will try to plant some trees around here in Quebec, Canada as a donation for your great work :)

**Comment by MoleMan1024** [comment]
@BenPicard : very kind of you, thanks!

**Comment by MoleMan1024** [comment]
integrated in version 2.4.5

**Comment by monkbroc** [comment]
I was able to make audio commands working on my XC40 Recharge after reading this issue. Could you please add a section to the FAQ on the website like this:

Audio commands respond by suggesting to install Pandora/YouTube Music/etc.

If the Google Assistant responds to voice commands like "Play <track>" with a message like "To do that, you'll need to install <Pandora/YouTube Music/Spotify/iHeartRadio>", you need to change the music provider for Google Assistant. Download the Google Assistant on your phone with the same Google account as your car. In the settings, go to Music and select "No default provider." Then audio commands will be sent to AudioWagon when the app is running.
![Screenshot_20230702-130331_Google](https://github.com/MoleMan1024/audiowagon/assets/1919681/f60aec5f-9144-4462-b45b-87f234f78718)

**Comment by MoleMan1024** [comment]
@monkbroc : good idea, will add that
